# fly.toml app configuration file generated for mewt-backend on 2024-08-04T01:08:00Z

app = "mewt-backend"
primary_region = "fra"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "1s"
  interval = "15s"
  restart_limit = 0
  timeout = "2s"
  method = "get"
  path = "/status"

[env]
  PORT = "8000"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256